project_id = "pempjibekapukdoethro"

[functions.humanize]
verify_jwt = false

[functions.paystack-checkout]
verify_jwt = false

[functions.subscription-checkout]
verify_jwt = false

[functions.generate-cover-letter]
enabled = true
verify_jwt = true
import_map = "./functions/generate-cover-letter/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-cover-letter/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-cover-letter/*.html" ]

[functions.start-campaign]
enabled = true
verify_jwt = true
import_map = "./functions/start-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/start-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/start-campaign/*.html" ]

[functions.process-job]
enabled = true
verify_jwt = true
import_map = "./functions/process-job/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-job/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-job/*.html" ]
