project_id = "pempjibekapukdoethro"

[functions.humanize]
verify_jwt = false

[functions.paystack-checkout]
verify_jwt = false

[functions.subscription-checkout]
verify_jwt = false

[functions.generate-cover-letter]
enabled = true
verify_jwt = true
import_map = "./functions/generate-cover-letter/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-cover-letter/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-cover-letter/*.html" ]

[functions.start-campaign]
enabled = true
verify_jwt = true
import_map = "./functions/start-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/start-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/start-campaign/*.html" ]

[functions.process-job]
enabled = true
verify_jwt = true
import_map = "./functions/process-job/deno.json"
entrypoint = "./functions/process-job/index.ts"

[functions.drip-batch]
enabled = true
verify_jwt = false
import_map = "./functions/drip-batch/deno.json"
entrypoint = "./functions/drip-batch/index.ts"

[functions.process-batch]
enabled = true
verify_jwt = true
import_map = "./functions/process-batch/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-batch/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-batch/*.html" ]

[functions.get-download-url]
enabled = true
verify_jwt = true
import_map = "./functions/get-download-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-download-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-download-url/*.html" ]

[functions.initialize-paystack-product]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-paystack-product/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-paystack-product/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-paystack-product/*.html" ]

[functions.claim-free-product]
enabled = true
verify_jwt = true
import_map = "./functions/claim-free-product/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/claim-free-product/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/claim-free-product/*.html" ]

[functions.generate-application-summary]
enabled = true
verify_jwt = true
import_map = "./functions/generate-application-summary/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-application-summary/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-application-summary/*.html" ]

[functions.get-summary-url]
enabled = true
verify_jwt = true
import_map = "./functions/get-summary-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-summary-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-summary-url/*.html" ]
