import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "Is there a money-back guarantee?",
    a: "We offer a 'Human-Touch' Quality Guarantee: If you aren't satisfied with the quality of your first 5 applications, we'll stop the mission and give you a 100% refund. Because our career specialists begin manual work immediately, missions are non-refundable once the 10th application is deployed. We also offer full refunds if our team determines your initial resume isn't yet ready for a professional launch.",
  },
  {
    q: "How does the Human-in-the-Loop review work?",
    a: "Every application generated by our AI is reviewed by a trained career specialist before submission. They personalize key paragraphs, verify tone alignment, and add company-specific insights. You can see their notes in the 'Human Touch' tooltip on each application.",
  },
  {
    q: "What is the turnaround time for applications?",
    a: "Most batches of 200 applications are processed and submitted within 7 business days. Priority applications receive expedited human review within 24 hours.",
  },
  {
    q: "Is my data secure?",
    a: "All data is encrypted in transit (TLS 1.3) and at rest (AES-256). We are SOC 2 compliant, and no AI models are trained on your personal data. See our Privacy Policy for full details.",
  },
  {
    q: "Can I use multiple resumes for different roles?",
    a: "Absolutely! Our Multi-Resume Identity Vault lets you upload up to 5 resume versions. Set a primary and our system matches the best version to each application.",
  },
];

const FAQSection = () => {
  return (
    <section className="py-24 md:py-32">
      <div className="container mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16 text-center"
        >
          <p className="mb-3 text-sm font-medium uppercase tracking-widest text-primary">
            FAQ
          </p>
          <h2
            className="text-3xl font-bold text-foreground md:text-4xl"
            style={{ fontFamily: "'Playfair Display', serif" }}
          >
            Frequently Asked Questions
          </h2>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mx-auto max-w-2xl"
        >
          <Accordion type="single" collapsible className="space-y-0">
            {faqs.map((faq, i) => (
              <AccordionItem
                key={i}
                value={`faq-${i}`}
                className="border-b border-border/30 px-0"
              >
                <AccordionTrigger
                  className="py-5 text-left text-base font-medium text-foreground hover:no-underline"
                  style={{ fontFamily: "'Playfair Display', serif" }}
                >
                  {faq.q}
                </AccordionTrigger>
                <AccordionContent className="pb-5 text-sm leading-relaxed text-muted-foreground">
                  {faq.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
};

export default FAQSection;
