// Data-driven config for the ad-funnel onboarding quiz.
// `icon` values are lucide-react icon names (looked up via icons.jsx),
// never emoji. `kicker` is the short uppercase label shown above the
// headline (replaces the old giant emoji + caption pattern).

export const QUIZ_STEPS = [
  {
    id: 'goal',
    stage: 'Profile',
    kicker: 'Goal',
    icon: 'Target',
    type: 'single',
    title: "What's your goal?",
    subtitle: "We'll customize your experience based on this",
    options: [
      { value: 'new-job', label: 'Land a new job', icon: 'Briefcase' },
      { value: 'internship', label: 'Internship placement', icon: 'GraduationCap' },
      { value: 'career-change', label: 'Change careers', icon: 'Repeat' },
      { value: 'better-salary', label: 'Get a better salary', icon: 'DollarSign' },
      { value: 'first-job', label: 'Find my first job', icon: 'Footprints' },
    ],
  },
  {
    id: 'personalize',
    stage: 'Profile',
    kicker: 'About you',
    icon: 'User',
    type: 'form',
    title: "Let's personalize your experience",
    subtitle: 'Tell us a bit about yourself',
    fields: [
      { name: 'firstName', label: "What's your first name?", placeholder: 'Enter your name', type: 'text' },
      { name: 'email', label: "What's your email address?", placeholder: 'Enter your email', type: 'email' },
    ],
    multiSelectField: {
      name: 'industry',
      label: 'What industry are you in?',
      options: [
        { value: 'technology', label: 'Technology', icon: 'Laptop' },
        { value: 'finance', label: 'Finance', icon: 'LineChart' },
        { value: 'healthcare', label: 'Healthcare', icon: 'HeartPulse' },
        { value: 'marketing', label: 'Marketing', icon: 'Megaphone' },
        { value: 'sales', label: 'Sales', icon: 'Briefcase' },
        { value: 'design', label: 'Design', icon: 'Palette' },
        { value: 'engineering', label: 'Engineering', icon: 'Settings' },
        { value: 'other', label: 'Other', icon: 'Star' },
      ],
    },
  },
  {
    id: 'jobSearchStatus',
    stage: 'Context',
    kicker: 'Job search',
    icon: 'Search',
    type: 'single',
    title: 'Where are you in your job search?',
    subtitle: 'This helps us understand your needs',
    options: [
      { value: 'actively-searching', label: 'Actively searching', sub: 'Applying daily', icon: 'Search' },
      { value: 'casually-looking', label: 'Casually looking', sub: 'Open to opportunities', icon: 'Eye' },
      { value: 'just-starting', label: 'Just getting started', sub: 'Beginning my search', icon: 'Sprout' },
      { value: 'frustrated', label: 'Frustrated & stuck', sub: 'Need help breaking through', icon: 'Frown' },
    ],
  },
  {
    id: 'challenges',
    stage: 'Context',
    kicker: 'Challenges',
    icon: 'AlertTriangle',
    type: 'multi',
    title: "What's your biggest challenge?",
    subtitle: 'Select all that apply',
    options: [
      { value: 'no-responses', label: 'Not getting responses', sub: '73% of job seekers', icon: 'ThumbsDown' },
      { value: 'time-consuming', label: 'Too time consuming', sub: '4+ hours daily', icon: 'Clock' },
      { value: 'cover-letters', label: 'Writing cover letters', sub: 'Most dreaded task', icon: 'FileText' },
      { value: 'staying-organized', label: 'Staying organized', sub: '60% lose track', icon: 'LayoutGrid' },
      { value: 'confidence', label: 'Lack of confidence', sub: 'After 50+ rejections', icon: 'ShieldAlert' },
    ],
    footerNote: "We've helped thousands of job seekers overcome these exact challenges.",
  },
  {
    id: 'appsSent',
    stage: 'Context',
    kicker: 'Volume',
    icon: 'Mail',
    type: 'single',
    title: 'How many applications have you sent?',
    subtitle: 'In your current job search',
    options: [
      { value: '0-10', label: '0-10', sub: 'Just starting out' },
      { value: '11-50', label: '11-50', sub: 'Getting going' },
      { value: '51-100', label: '51-100', sub: 'Making progress' },
      { value: '100+', label: '100+', sub: 'Veteran applicant' },
    ],
    footerNote: 'The average job seeker needs to send 100-200 applications to land a job in 2026.',
  },
  {
    id: 'timePerApp',
    stage: 'Context',
    kicker: 'Time investment',
    icon: 'Clock',
    type: 'single',
    title: 'How long does each application take you?',
    subtitle: 'Including research, tailoring resume & cover letter',
    options: [
      { value: '15-30', label: '15-30 mins', icon: 'Zap', numericValue: 22 },
      { value: '30-60', label: '30-60 mins', icon: 'Timer', numericValue: 45 },
      { value: '60-90', label: '1-1.5 hours', icon: 'Meh', numericValue: 75 },
      { value: '90+', label: '1.5+ hours', icon: 'Frown', numericValue: 105 },
    ],
    insight: (selectedOption) => {
      const minutes = selectedOption?.numericValue || 45;
      const hours = ((minutes * 50) / 60).toFixed(1);
      return {
        label: 'Time Reality Check',
        value: `${hours} hours`,
        sub: "That's how long 100 applications would take you, manually",
      };
    },
  },
  {
    id: 'role',
    stage: 'Targeting',
    kicker: 'Target role',
    icon: 'Briefcase',
    type: 'single',
    grid: true,
    title: 'What type of role are you targeting?',
    subtitle: "We'll tailor applications to match",
    options: [
      { value: 'software-engineer', label: 'Software Engineer', icon: 'Code2' },
      { value: 'product-manager', label: 'Product Manager', icon: 'Package' },
      { value: 'designer', label: 'Designer', icon: 'Palette' },
      { value: 'data-analyst', label: 'Data Analyst', icon: 'BarChart3' },
      { value: 'marketing', label: 'Marketing', icon: 'Megaphone' },
      { value: 'sales', label: 'Sales', icon: 'Briefcase' },
      { value: 'operations', label: 'Operations', icon: 'Settings' },
      { value: 'software-intern', label: 'Software Intern', icon: 'Laptop' },
    ],
  },
  { id: 'socialProof', stage: 'Targeting', kicker: 'Proof', icon: 'Star', type: 'social-proof' },
  { id: 'realityCheck', stage: 'Targeting', kicker: 'Insight', icon: 'Sparkles', type: 'reality-check' },
  {
    id: 'responseRate',
    stage: 'Targeting',
    kicker: 'Performance',
    icon: 'TrendingUp',
    type: 'single',
    title: "What's your current response rate?",
    subtitle: 'Interviews per 100 applications',
    ctaLabel: 'See How We Can Help',
    options: [
      { value: '0-5', label: '0-5%', sub: 'Below average', icon: 'TrendingDown' },
      { value: '5-10', label: '5-10%', sub: 'Average', icon: 'TrendingUp' },
      { value: '10-20', label: '10-20%', sub: 'Good', icon: 'TrendingUp' },
      { value: '20+', label: '20%+', sub: 'Excellent', icon: 'TrendingUp' },
    ],
  },
  {
    id: 'experienceLevel',
    stage: 'Targeting',
    kicker: 'Experience',
    icon: 'BarChart3',
    type: 'single',
    title: "What's your experience level?",
    subtitle: 'This helps us match you with the right roles',
    options: [
      { value: 'intern', label: 'Intern', sub: 'Currently studying', icon: 'GraduationCap', track: 'intern' },
      { value: 'entry', label: 'Entry Level', sub: '0-2 years', icon: 'Sprout', track: 'professional' },
      { value: 'mid', label: 'Mid Level', sub: '3-5 years', icon: 'Leaf', track: 'professional' },
      { value: 'senior', label: 'Senior', sub: '6-10 years', icon: 'TreePine', track: 'professional' },
      { value: 'executive', label: 'Executive', sub: '10+ years', icon: 'Mountain', track: 'professional' },
    ],
  },
  { id: 'loading', stage: 'Plan', kicker: 'Plan', icon: 'Brain', type: 'loading' },
];
