import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Send, Mail, Clock, Loader2, HelpCircle, MessageSquare, ChevronDown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { CHART, T, Panel, PanelHeader } from "@/admin/ui/system";
import { useRamp } from "@/admin/ui/charts";

const SUPPORT_EMAIL = "support@jobapp.com";

const faqs = [
  {
    q: "How does the Human-in-the-Loop review work?",
    a: "Every application generated by our AI is reviewed by a trained career specialist before submission. They personalize key paragraphs, verify tone alignment, and add company-specific insights.",
  },
  {
    q: "What is the turnaround time?",
    a: "Most batches of 200 applications are processed within 3-5 business days. Priority applications receive expedited review within 24 hours.",
  },
  {
    q: "Can I edit a submitted application?",
    a: "Once marked as 'Submitted,' applications cannot be modified. However, you can update your resume and preferences for future applications.",
  },
  {
    q: "How do I request a refund?",
    a: "We offer a 'Human-Touch' Quality Guarantee: if you aren't satisfied with your first 5 applications, we'll stop the mission and give you a 100% refund. See our full Refund & Satisfaction Policy for details.",
  },
  {
    q: "Is there a money-back guarantee?",
    a: "We offer a 'Human-Touch' Quality Guarantee: If you aren't satisfied with the quality of your first 5 applications, we'll stop the mission and give you a 100% refund. Because our career specialists begin manual work immediately, missions are non-refundable once the 10th application is deployed.",
  },
  {
    q: "Is my data secure?",
    a: "All data is encrypted with TLS 1.3 in transit and AES-256 at rest. We are SOC 2 compliant and no AI models are trained on your data.",
  },
  {
    q: "Can I use multiple resumes?",
    a: "Yes! The Resume Manager lets you upload up to 5 versions. Set a primary and our system matches the best version to each application.",
  },
];

/** Shared field chrome so the three inputs can't drift apart. */
const FIELD = `w-full rounded-lg border bg-[#FAFAF8] px-3 py-2 text-[12.5px] outline-none
               placeholder:text-[#9A9995] focus:border-[#C9C8C2] disabled:opacity-60
               dark:bg-white/[0.03] dark:focus:border-white/25`;

const Support = () => {
  const { dark } = useRamp();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [sending, setSending] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const { toast } = useToast();

  const accent = dark ? CHART.accentDark : CHART.accent;

  const handleSend = async () => {
    if (!name.trim()) {
      toast({ title: "Missing name", description: "Please enter your name.", variant: "destructive" });
      return;
    }
    if (!email.trim() || !/^\S+@\S+\.\S+$/.test(email)) {
      toast({ title: "Invalid email", description: "Please enter a valid email address.", variant: "destructive" });
      return;
    }
    if (!message.trim()) {
      toast({ title: "Empty message", description: "Please type a message.", variant: "destructive" });
      return;
    }

    try {
      setSending(true);

      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) throw new Error("Not authenticated");

      // 1. Insert into support_messages
      const { error: messageError } = await supabase
        .from("support_messages")
        .insert({
          user_id: user.id,
          name: name.trim(),
          email: email.trim(),
          message: message.trim(),
          status: "open",
        });

      if (messageError) throw messageError;

      // 2. Insert into admin_notifications so admin sees it
      const { error: notifError } = await supabase
        .from("admin_notifications")
        .insert({
          type: "support_message",
          title: `New support message from ${name.trim()}`,
          message: message.trim(),
          user_id: user.id,
          is_read: false,
        });

      if (notifError) throw notifError;

      // Clear form
      setName("");
      setEmail("");
      setMessage("");

      toast({
        title: "Message Sent ✓",
        description: "A Career Coach will respond within 24 hours.",
      });
    } catch (err) {
      console.error("Support message error:", err);
      toast({
        title: "Failed to send message",
        description: err instanceof Error ? err.message : "Something went wrong. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSending(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-4">
        <div>
          <h1 className={`text-[20px] font-bold tracking-[-0.01em] ${T.ink}`}>Support Hub</h1>
          <p className={`text-[12px] ${T.muted}`}>Get help from our team or browse FAQs.</p>
        </div>

        <div className="grid items-start gap-4 lg:grid-cols-2">
          {/* ── FAQ ────────────────────────────────────────────────────────── */}
          <Panel className="overflow-hidden">
            <PanelHeader
              icon={HelpCircle}
              title="Frequently asked questions"
              right={<span className={`text-[11px] ${T.muted}`}>{faqs.length} answers</span>}
            />

            <div className={`divide-y ${T.divide} border-t ${T.hairline}`}>
              {faqs.map((faq, i) => {
                const open = openFaq === i;
                return (
                  <div key={faq.q}>
                    <button
                      type="button"
                      onClick={() => setOpenFaq(open ? null : i)}
                      aria-expanded={open}
                      className={`flex w-full items-center justify-between gap-3 px-5 py-3.5
                                  text-left transition-colors ${T.hover}`}
                    >
                      <span className={`text-[12.5px] font-semibold leading-snug ${T.ink}`}>
                        {faq.q}
                      </span>
                      <ChevronDown
                        size={14}
                        className={`shrink-0 transition-transform duration-200 ${T.muted}
                                    ${open ? "rotate-180" : ""}`}
                      />
                    </button>

                    <AnimatePresence initial={false}>
                      {open && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.18 }}
                          className="overflow-hidden"
                        >
                          <p className={`px-5 pb-4 text-[12px] leading-relaxed ${T.ink2}`}>
                            {faq.a}
                          </p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          </Panel>

          {/* ── Contact ────────────────────────────────────────────────────── */}
          <Panel>
            <PanelHeader
              icon={MessageSquare}
              title="Talk to a career coach"
              right={
                <span
                  className={`inline-flex items-center gap-1 rounded-md border ${T.hairline}
                              px-1.5 py-0.5 text-[10.5px] font-semibold ${T.ink2}`}
                >
                  <Clock size={10} />
                  ~24hr reply
                </span>
              }
            />

            <div className="space-y-3 px-5 pb-5">
              {/* Mailto, so the address is usable rather than just displayed. */}
              <a
                href={`mailto:${SUPPORT_EMAIL}`}
                className={`flex items-center gap-2 rounded-lg border ${T.hairline} px-3 py-2.5
                            transition-colors hover:bg-[#FAFAF8] dark:hover:bg-white/5`}
              >
                <Mail size={14} style={{ color: accent }} className="shrink-0" />
                <span className={`truncate text-[12.5px] font-medium ${T.ink}`}>
                  {SUPPORT_EMAIL}
                </span>
              </a>

              <div className="grid gap-3 sm:grid-cols-2">
                <div className="space-y-1.5">
                  <label
                    htmlFor="support-name"
                    className={`block text-[10.5px] font-semibold uppercase tracking-[0.08em] ${T.muted}`}
                  >
                    Your name
                  </label>
                  <input
                    id="support-name"
                    placeholder="Jane Doe"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    disabled={sending}
                    className={`${FIELD} ${T.hairline} ${T.ink}`}
                  />
                </div>

                <div className="space-y-1.5">
                  <label
                    htmlFor="support-email"
                    className={`block text-[10.5px] font-semibold uppercase tracking-[0.08em] ${T.muted}`}
                  >
                    Email address
                  </label>
                  <input
                    id="support-email"
                    type="email"
                    placeholder="jane@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={sending}
                    className={`${FIELD} ${T.hairline} ${T.ink}`}
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <label
                  htmlFor="support-message"
                  className={`block text-[10.5px] font-semibold uppercase tracking-[0.08em] ${T.muted}`}
                >
                  Message
                </label>
                <textarea
                  id="support-message"
                  placeholder="How can we help you?"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  disabled={sending}
                  className={`${FIELD} ${T.hairline} ${T.ink} min-h-[132px] resize-none leading-relaxed`}
                />
              </div>

              <button
                type="button"
                onClick={handleSend}
                disabled={sending}
                className="inline-flex w-full items-center justify-center gap-1.5 rounded-lg
                           bg-[#111110] px-3 py-2.5 text-[12.5px] font-semibold text-white
                           transition-opacity hover:opacity-90 disabled:opacity-50
                           dark:bg-white dark:text-[#111110]"
              >
                {sending ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                {sending ? "Sending…" : "Send message"}
              </button>

              <p className={`text-[11px] leading-relaxed ${T.muted}`}>
                Your message goes straight to the coaching team — no ticket queue, no bots.
              </p>
            </div>
          </Panel>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default Support;
