import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { useState } from "react";
import { Send, Mail, Clock, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

const faqs = [
  {
    q: "How does the Human-in-the-Loop review work?",
    a: "Every application generated by our AI is reviewed by a trained career specialist before submission. They personalize key paragraphs, verify tone alignment, and add company-specific insights.",
  },
  {
    q: "What is the turnaround time?",
    a: "Most batches of 200 applications are processed within 3-5 business days. Priority applications receive expedited review within 24 hours.",
  },
  {
    q: "Can I edit a submitted application?",
    a: "Once marked as 'Submitted,' applications cannot be modified. However, you can update your resume and preferences for future applications.",
  },
  {
    q: "How do I request a refund?",
    a: "We offer a 'Human-Touch' Quality Guarantee: if you aren't satisfied with your first 5 applications, we'll stop the mission and give you a 100% refund. See our full Refund & Satisfaction Policy for details.",
  },
  {
    q: "Is there a money-back guarantee?",
    a: "We offer a 'Human-Touch' Quality Guarantee: If you aren't satisfied with the quality of your first 5 applications, we'll stop the mission and give you a 100% refund. Because our career specialists begin manual work immediately, missions are non-refundable once the 10th application is deployed.",
  },
  {
    q: "Is my data secure?",
    a: "All data is encrypted with TLS 1.3 in transit and AES-256 at rest. We are SOC 2 compliant and no AI models are trained on your data.",
  },
  {
    q: "Can I use multiple resumes?",
    a: "Yes! The Resume Manager lets you upload up to 5 versions. Set a primary and our system matches the best version to each application.",
  },
];

const Support = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [sending, setSending] = useState(false);
  const { toast } = useToast();

  const handleSend = async () => {
    if (!name.trim()) {
      toast({ title: "Missing name", description: "Please enter your name.", variant: "destructive" });
      return;
    }
    if (!email.trim() || !/^\S+@\S+\.\S+$/.test(email)) {
      toast({ title: "Invalid email", description: "Please enter a valid email address.", variant: "destructive" });
      return;
    }
    if (!message.trim()) {
      toast({ title: "Empty message", description: "Please type a message.", variant: "destructive" });
      return;
    }

    try {
      setSending(true);

      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) throw new Error("Not authenticated");

      // 1. Insert into support_messages
      const { error: messageError } = await supabase
        .from("support_messages")
        .insert({
          user_id: user.id,
          name: name.trim(),
          email: email.trim(),
          message: message.trim(),
          status: "open",
        });

      if (messageError) throw messageError;

      // 2. Insert into admin_notifications so admin sees it
      const { error: notifError } = await supabase
        .from("admin_notifications")
        .insert({
          type: "support_message",
          title: `New support message from ${name.trim()}`,
          message: message.trim(),
          user_id: user.id,
          is_read: false,
        });

      if (notifError) throw notifError;

      // Clear form
      setName("");
      setEmail("");
      setMessage("");

      toast({
        title: "Message Sent ✓",
        description: "A Career Coach will respond within 24 hours.",
      });
    } catch (err) {
      console.error("Support message error:", err);
      toast({
        title: "Failed to send message",
        description: err instanceof Error ? err.message : "Something went wrong. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSending(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Support Hub</h1>
          <p className="text-sm text-muted-foreground">
            Get help from our team or browse FAQs.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* FAQ */}
          <div className="glass-card rounded-xl p-6">
            <h3 className="mb-4 text-sm font-semibold text-foreground">
              Frequently Asked Questions
            </h3>
            <Accordion type="single" collapsible className="space-y-1">
              {faqs.map((faq, i) => (
                <AccordionItem
                  key={i}
                  value={`faq-${i}`}
                  className="rounded-lg border border-border/30 bg-muted/20 px-4"
                >
                  <AccordionTrigger className="py-3 text-left text-sm font-medium text-foreground hover:no-underline">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="pb-3 text-sm leading-relaxed text-muted-foreground">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>

          {/* Contact Form */}
          <div className="glass-card rounded-xl p-6">
            <div className="mb-4 flex items-center gap-3">
              <h3 className="text-sm font-semibold text-foreground">
                Talk to a Human Career Coach
              </h3>
              <Badge variant="human" className="text-[10px]">
                <Clock className="mr-0.5 h-2.5 w-2.5" /> ~24hr response
              </Badge>
            </div>

            <div className="mb-4 flex items-center gap-2 rounded-lg border border-border/30 bg-muted/20 p-3">
              <Mail className="h-4 w-4 text-primary" />
              <span className="text-sm text-muted-foreground">support@jobapp.com</span>
            </div>

            <div className="space-y-3">
              <Input
                placeholder="Your name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="bg-muted/50"
                disabled={sending}
              />
              <Input
                placeholder="Email address"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="bg-muted/50"
                disabled={sending}
              />
              <Textarea
                placeholder="How can we help you?"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                className="min-h-[120px] resize-none bg-muted/50"
                disabled={sending}
              />
              <Button
                variant="hero"
                className="w-full gap-2"
                onClick={handleSend}
                disabled={sending}
              >
                {sending ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Sending...
                  </>
                ) : (
                  <>
                    <Send className="h-4 w-4" />
                    Send Message
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default Support;