import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { MessageCircle, Send, HelpCircle, ChevronRight } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const faqs = [
  {
    q: "How does the Human-in-the-Loop review work?",
    a: "Every application generated by our AI is reviewed by a trained career specialist before submission. They personalize key paragraphs, verify tone alignment, and add company-specific insights. You can see their notes in the 'Human Touch' tooltip on each application.",
  },
  {
    q: "What is the turnaround time for applications?",
    a: "Most batches of 200 applications are processed and submitted within 3-5 business days. Priority applications (marked as 'Interview' status) receive expedited human review within 24 hours.",
  },
  {
    q: "Can I edit an application after it's been submitted?",
    a: "Once an application is marked as 'Submitted,' it cannot be modified. However, you can update your resume and preferences at any time, and future applications will use the updated materials.",
  },
  {
    q: "How do I request a refund?",
    a: "We offer a 7-day satisfaction guarantee from your first application batch. Contact our support team through this panel or email refunds@jobapp.com within the refund window.",
  },
  {
    q: "Is my data secure?",
    a: "Yes. All data is encrypted in transit (TLS 1.3) and at rest (AES-256). We are SOC 2 compliant, and no AI models are trained on your personal data. See our Privacy Policy for full details.",
  },
  {
    q: "Can I use multiple resumes for different roles?",
    a: "Absolutely! Our Multi-Resume Identity Vault lets you upload up to 5 resume versions. You can set a primary resume and our system will match the best version to each application.",
  },
];

const SupportPanel = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  const { toast } = useToast();

  const handleSend = () => {
    if (!message.trim()) {
      toast({ title: "Empty message", description: "Please type a message.", variant: "destructive" });
      return;
    }
    setSent(true);
    toast({ title: "Message Sent ✓", description: "A Career Coach will respond within 24 hours." });
    setTimeout(() => {
      setName("");
      setEmail("");
      setMessage("");
      setSent(false);
    }, 3000);
  };

  return (
    <Sheet>
      <SheetTrigger asChild>
        <motion.button
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 1, type: "spring", stiffness: 200 }}
          className="fixed bottom-6 right-6 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg transition-transform hover:scale-110"
          style={{ boxShadow: "0 0 25px hsl(213 94% 55% / 0.4)" }}
          aria-label="Open support"
        >
          <MessageCircle className="h-6 w-6" />
        </motion.button>
      </SheetTrigger>

      <SheetContent className="w-full border-border/50 bg-card sm:max-w-md">
        <SheetHeader className="mb-6">
          <SheetTitle className="flex items-center gap-2 text-foreground">
            <HelpCircle className="h-5 w-5 text-primary" />
            Talk to a Human Career Coach
          </SheetTitle>
          <p className="text-sm text-muted-foreground">
            Get answers fast or connect directly with our team.
          </p>
        </SheetHeader>

        {/* FAQ Section */}
        <div className="mb-6">
          <h4 className="mb-3 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wider text-muted-foreground">
            <ChevronRight className="h-3 w-3" />
            Frequently Asked Questions
          </h4>
          <Accordion type="single" collapsible className="space-y-1">
            {faqs.map((faq, i) => (
              <AccordionItem key={i} value={`faq-${i}`} className="rounded-lg border border-border/30 bg-muted/20 px-4">
                <AccordionTrigger className="py-3 text-left text-sm font-medium text-foreground hover:no-underline">
                  {faq.q}
                </AccordionTrigger>
                <AccordionContent className="pb-3 text-sm leading-relaxed text-muted-foreground">
                  {faq.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        {/* Direct Message Section */}
        <div className="glass-card rounded-xl p-5">
          <div className="mb-4 flex items-center gap-2">
            <Badge variant="human" className="text-xs">Direct Message</Badge>
            <span className="text-xs text-muted-foreground">Avg. response: &lt;24hrs</span>
          </div>

          <AnimatePresence mode="wait">
            {sent ? (
              <motion.div
                key="sent"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center gap-3 py-8 text-center"
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-status-interview/15">
                  <Send className="h-5 w-5 text-status-interview" />
                </div>
                <p className="text-sm font-medium text-foreground">Message Sent!</p>
                <p className="text-xs text-muted-foreground">A Career Coach will respond within 24 hours.</p>
              </motion.div>
            ) : (
              <motion.div
                key="form"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="space-y-3"
              >
                <Input
                  placeholder="Your name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="bg-muted/50"
                />
                <Input
                  placeholder="Email address"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="bg-muted/50"
                />
                <Textarea
                  placeholder="How can we help you?"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  className="min-h-[100px] resize-none bg-muted/50"
                />
                <Button variant="hero" className="w-full gap-2" onClick={handleSend}>
                  <Send className="h-4 w-4" />
                  Send Message
                </Button>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </SheetContent>
    </Sheet>
  );
};

export default SupportPanel;
